//
// Created by cjp on 1/10/23.
//

#ifndef TERROIR_MOUSEBUTTONCODES_H
#define TERROIR_MOUSEBUTTONCODES_H

#define TERR_MOUSE_BUTTON_1         0
#define TERR_MOUSE_BUTTON_2         1
#define TERR_MOUSE_BUTTON_3         2
#define TERR_MOUSE_BUTTON_4         3
#define TERR_MOUSE_BUTTON_5         4
#define TERR_MOUSE_BUTTON_6         5
#define TERR_MOUSE_BUTTON_7         6
#define TERR_MOUSE_BUTTON_8         7
#define TERR_MOUSE_BUTTON_LAST      GLFW_MOUSE_BUTTON_8
#define TERR_MOUSE_BUTTON_LEFT      GLFW_MOUSE_BUTTON_1
#define TERR_MOUSE_BUTTON_RIGHT     GLFW_MOUSE_BUTTON_2
#define TERR_MOUSE_BUTTON_MIDDLE    GLFW_MOUSE_BUTTON_3

#endif //TERROIR_MOUSEBUTTONCODES_H
